In [1]:

import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
np.all(a != 0)
# ninguno de los elementos es cero

np.True_

In [3]:
a = np.array([0, 0, 2, 0])
np.any(a != 0)
# existe al menos un elemento distinto de cero

np.True_

In [4]:
a = np.array([1, 2, np.nan, np.inf])
np.isnan(a), np.isinf(a)
# detecta valores NaN e infinitos

(array([False, False,  True, False]), array([False, False, False,  True]))

In [5]:
a = np.array([1, 2, np.inf])
np.isinf(a).any()
# contiene valores infinitos

np.True_

In [6]:
a = np.array([1, np.nan, 3])
np.isnan(a).any()
# contiene valores NaN

np.True_

In [7]:
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
a > b, a >= b, a < b, a <= b
# comparación elemento a elemento

(array([False, False,  True]),
 array([False,  True,  True]),
 array([ True, False, False]),
 array([ True,  True, False]))

In [8]:
a = np.array([1, 7, 13, 105])
a.nbytes
# memoria ocupada en bytes

32

In [9]:
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10, 5)
zeros, ones, fives

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [10]:
a = np.arange(30, 71)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [11]:
a = np.arange(30, 71, 2)
a

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.rand()

0.20578316517599193

In [14]:
np.random.randn(15)

array([-1.15819697e-01, -1.78688767e+00,  8.21639428e-01,  9.35021284e-01,
       -7.04667813e-02,  4.43746379e-01,  1.51041542e-03, -8.07677857e-01,
       -9.34579913e-02,  5.80076268e-01, -2.25291897e-03,  8.99465744e-01,
        6.75221466e-01,  3.92081292e-01,  4.41795580e-01])

In [15]:
a = np.arange(15, 56)
a[1:-1]


array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [16]:
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [17]:
a = np.arange(0, 21)
a[9:16] *= -1
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [18]:
a = np.array([1, 2, 3])
a.tolist()

[1, 2, 3]

In [19]:
l = [1, 2, 3]
np.array(l)

array([1, 2, 3])

In [20]:
m = np.array([[1, 2], [3, 4]])
m % 2 == 0

array([[False,  True],
       [False,  True]])

In [21]:
m = np.array([[1, 2, 3], [4, 5, 6]])
m.shape

(2, 3)